### ISSUE TITLE
Update opentelemetry-disk-buffering to use protobuf-javalite

### ISSUE THREAD

**Issue by danielbanks** [open-telemetry/opentelemetry-java-contrib#1009]
## Description

When using `io.opentelemetry.contrib:opentelemetry-disk-buffering` on Android and the [protodatastore] library(https://developer.android.com/topic/libraries/architecture/datastore), we get dependency resolution errors.

Protodatastore is a library provided by Google used by many Android applications.

The Android library is built using,
`com.google.protobuf:protobuf-kotlin-lite:`

which in turn consumes,
`com.google.protobuf:protobuf-javalite`

The issue is that the disk buffering lib consumes, 
`com.google.protobuf:protobuf-java`, 
rather than the light version.  

This means we get duplicate classes found and a build time dependency resolution error.

### Describe the solution you'd like

Given that the lite version of this is optimized for mobile and also that Mobile applications are most likely to make use of this disk export, can we upgrade the disk buffering library to use the lite version? Or provide an alternative that depends upon protobuf-javalite?

**Comment by danielbanks** [comment]
@LikeTheSalad I raised a feature request as per our discussion on slack :)

**Comment by LikeTheSalad** [comment]
Hi! - This issue should be fixed by https://github.com/open-telemetry/opentelemetry-java-contrib/pull/1008 which will be available in the next release (1.30.0-alpha if I'm not mistaken).

**Comment by trask** [comment]
1.30.0-alpha is just now released
