### ISSUE TITLE
Make v. Gradle tasks

### ISSUE THREAD

**Issue by rmfitzpatrick** [open-telemetry/opentelemetry-java-contrib#11]
Re: https://github.com/open-telemetry/opentelemetry-java-contrib/pull/10#discussion_r491269068 the adoption of Make in this project may be a point of contention or usability hindrance.  Usage of Make isn't standardized across Otel, but is used.

Available:
https://github.com/open-telemetry/opentelemetry-java
https://github.com/open-telemetry/opentelemetry-proto
https://github.com/open-telemetry/opentelemetry-go
https://github.com/open-telemetry/opentelemetry-go-contrib
https://github.com/open-telemetry/opentelemetry-php
https://github.com/open-telemetry/opentelemetry-collector
https://github.com/open-telemetry/opentelemetry-collector-contrib
https://github.com/open-telemetry/opentelemetry.io

Unavailable:
https://github.com/open-telemetry/opentelemetry-java-instrumentation
https://github.com/open-telemetry/opentelemetry-js
https://github.com/open-telemetry/opentelemetry-js-contrib
https://github.com/open-telemetry/opentelemetry-python (except docs)
https://github.com/open-telemetry/opentelemetry-ruby
https://github.com/open-telemetry/opentelemetry-cpp
https://github.com/open-telemetry/opentelemetry-rust
https://github.com/open-telemetry/opentelemetry-dotnet
https://github.com/open-telemetry/opentelemetry-dotnet-contrib
https://github.com/open-telemetry/opentelemetry-erlang
https://github.com/open-telemetry/opentelemetry-erlang-api

Of the projects using it, four are in golang and two others are polyglot, where Make could be a natural choice.  Java projects are split in usage.

Should we continue to use Make or should we only adopt direct `gradlew` usage?  In the hope to avoid bikeshedding, we should be mainly concerned where the stability, maintainability, and general accessibility of the project are in potential jeopardy.

My 2¢:  I like the relatively intuitive nature of Make as a standardize interface and don't see its usage as an issue.  It also plays nicely w/ my shell's completion/suggestion plugin where gradle does not.  If gradle is adopted, then at the least we should define and document high level tasks similar to the current make targets to prevent loaded invocations.

**Comment by trask** [comment]
> Available:
> https://github.com/open-telemetry/opentelemetry-java

I'm surprised Makefile is used in Java repo, @jkwatson / @anuraaga?

**Comment by jkwatson** [comment]
> > Available:
> > https://github.com/open-telemetry/opentelemetry-java
> 
> I'm surprised Makefile is used in Java repo, @jkwatson / @anuraaga?

It pre-dates my involvement. I just use the gradle tasks, since the makefile just calls them.

**Comment by anuraaga** [comment]
Yeah I don't think I ever even noticed the Makefile in Java and would be inclined to remove it.

- Gradle is a task runner, having another task runner is extra complexity. I would say Gradle is idiomatic in Java and Make isn't.

- Make isn't cross platform (Windows it's quite a lot of steps to get it, Mac does it have it without installing xcode? Not sure). For a Java project, there's no reason to worry about the issue of cross platformness since we can just use Gradle instead.

**Comment by rmfitzpatrick** [comment]
Finally got around to this: https://github.com/open-telemetry/opentelemetry-java-contrib/commit/9c7579e4cb4ea4df45a37b63473cf6bb9b8d64c8.  Thanks for the suggestions.
