### ISSUE TITLE
[jmx-metrics] Copypasta/incorrect reference to Cassandra

### ISSUE THREAD

**Issue by breedx-splk** [open-telemetry/opentelemetry-java-contrib#1348]
### What happened?

jvm.md here https://github.com/open-telemetry/opentelemetry-java-contrib/blob/main/jmx-metrics/docs/target-systems/jvm.md contains reference to Cassandra, which is inaccurate. I think it's just copypasta and can be edited.

### Component version

trunk/main

**Comment by jefchien** [comment]
The docs also don't reflect https://github.com/open-telemetry/opentelemetry-java-contrib/blob/main/jmx-metrics/src/main/resources/target-systems/jvm.groovy. The metric definition file only has `jvm.memory.heap`, `jvm.memory.nonheap`, and `jvm.memory.pool`. It doesn't have any of the `jvm.memory.heap.*`, `jvm.memory.nonheap.*`, or `jvm.memory.pool.*` metrics.
