### ISSUE TITLE
Add Support for Multiple Attributes

### ISSUE THREAD

**Issue by Mrod1598** [open-telemetry/opentelemetry-java-contrib#136]
**Is your feature request related to a problem? Please describe.**
Add Ability to pass in multiple Attributes into one `otel.instrument()` call. 

**Describe the solution you'd like**
What I propose is adding additional signatures to otel.instrument that support attributes in the format of `Map<String, Map<String,String>>` where the strings represent `<Attribute, <LabelKey, LabelValue>>`

Example: 
currently what is required to collect this metric
```
otel.instrument(beantomcatconnectors, "tomcat.threads.idle", "description", "1",
    ["proto_handler" : { mbean -> mbean.name().getKeyProperty("name") }],
    "currentThreadCount", otel.&doubleValueObserver)
otel.instrument(beantomcatconnectors, "tomcat.threads.busy", "description", "1", 
    ["proto_handler" : { mbean -> mbean.name().getKeyProperty("name") }],
    "currentThreadsBusy", otel.&doubleValueObserver)
```
What it would like with the proposed solution
```
otel.instrument(beantomcatconnectors, "tomcat.threads", "description", "1",
    ["proto_handler" : { mbean -> mbean.name().getKeyProperty("name") }],
    ["currentThreadCount": ["Thread Type": "current"],
    "currentThreadsBusy": ["Thread Type": "busy"]], 
    otel.&doubleValueObserver)
```

**Comment by rmfitzpatrick** [comment]
@Mrod1598 I can see the use of this feature and think it can be helpful.  Wouldn't we want the attributes to map to label functions to keep with the current convention?  Otherwise we seem to be limiting the capabilities out of the gate imo.
