### ISSUE TITLE
Reuse add_metadata_from_filepath

### ISSUE THREAD

**Issue by zeitlinger** [open-telemetry/opentelemetry-java-contrib#1361]
### Component(s)

processors

### Is your feature request related to a problem? Please describe.

[add_metadata_from_filepath](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/pkg/stanza/docs/operators/container.md#add-metadata-from-file-path) is tied to the container operator.

### Describe the solution you'd like

Would it make sense to move this feature to [file consumer](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/d065d41b980812603841ecb70db1431cd3312b53/pkg/stanza/fileconsumer/config.go#L73), so that it can be reused, e.g. in [OTLP JSON File Receiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/otlpjsonfilereceiver/README.md)?

**Comment by zeitlinger** [comment]
@djaglowski

**Comment by djaglowski** [comment]
Should this be moved to collector contrib?

**Comment by zeitlinger** [comment]
> Should this be moved to collector contrib?

yes!

**Comment by djaglowski** [comment]
I don't have permissions to move the issue. Not sure who does. Mind just closing this and reopening a new one?

**Comment by zeitlinger** [comment]
closed in favor of https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/33912
