### ISSUE TITLE
release compatible with OpenTelemetry SDK 1.40.0

### ISSUE THREAD

**Issue by sdelamo** [open-telemetry/opentelemetry-java-contrib#1403]
### Component(s)

aws-resources, aws-xray

[Latest release, 1.37.0](https://github.com/open-telemetry/opentelemetry-java-contrib/releases/tag/v1.37.0) says it targets OpenTelemetry SDK 1.37.0

> This release targets the OpenTelemetry SDK 1.37.0.

However, there is no release targeting [OpenTelemetry SDK 1.40.0](https://github.com/open-telemetry/opentelemetry-java/releases/tag/v1.40.0).

### Describe the solution you'd like

A release targeting [OpenTelemetry SDK 1.40.0](https://github.com/open-telemetry/opentelemetry-java/releases/tag/v1.40.0).

**Comment by laurit** [comment]
This is a mistake in the release notes. Contrib release [1.37.0](https://github.com/open-telemetry/opentelemetry-java-contrib/releases/tag/v1.37.0) targets sdk 1.4.0.

**Comment by trask** [comment]
re-opening to fix the release automation

**Comment by driverpt** [comment]
Can we make this 1.41.0 instead? Because of the removal of `okhttp3` from `aws-resources`?

**Comment by laurit** [comment]
> Can we make this 1.41.0 instead? Because of the removal of `okhttp3` from `aws-resources`?

https://github.com/open-telemetry/opentelemetry-java-contrib/releases/tag/v1.38.0 targets sdk 1.41.0

**Comment by trask** [comment]
> re-opening to fix the release automation

resolved by #1426
