### ISSUE TITLE
Closing a JFR recording may throw an Exception

### ISSUE THREAD

**Issue by dsgrieve** [open-telemetry/opentelemetry-java-contrib#1410]
### Component(s)

jfr-connection

## Description
Calling the Recording#close() method may throw an exception if the FlightRecorder MXBean closeRecording function fails. 
The behavior of the original microsoft/jfr-streaming code was to swallow the exception. The behavior of the contributed code is different and this has caused a regression in an application that uses this module. 

## Expected Result
The close() method on a Recording should not throw an exception. 

### Component version

1.37.0

**Comment by dsgrieve** [comment]
PR #1412

**Comment by trask** [comment]
Resolved by #1412
