### ISSUE TITLE
is jvm.memory.pool.used by default value is in 0.0000 Double?

### ISSUE THREAD

**Issue by sophieyfang** [open-telemetry/opentelemetry-java-contrib#147]
Trying my luck here. I haven't dig into the code too much. One thing causes problem in our side is  jvm.memory.pool.used generates 0.0000 then integer, we have a little hard time on finding where this 0.0000 comes from.

Details on the issue is stated in: https://github.com/GoogleCloudPlatform/ops-agent/issues/288

**Comment by trask** [comment]
hi @sophieyfang! `jvm.memory.pool.used` appears to be registered as a long, so I'm not sure how it would be sending a double value:

https://github.com/open-telemetry/opentelemetry-java-contrib/blob/632081ce85a3c71a6eed037a9f26d205e6f7fdc4/jmx-metrics/src/main/resources/target-systems/jvm.groovy#L36-L39

**Comment by trask** [comment]
cc @rmfitzpatrick who knows more about this code in case I'm missing something, and @jsuereth who knows more about GCP

**Comment by rmfitzpatrick** [comment]
@sophieyfang I'd agree with what Trask has provided and don't immediately see how this could be the case given [the underlying api usage](https://github.com/open-telemetry/opentelemetry-java-contrib/blob/632081ce85a3c71a6eed037a9f26d205e6f7fdc4/jmx-metrics/src/main/groovy/io/opentelemetry/contrib/jmxmetrics/GroovyMetricEnvironment.java#L353). A superficial validation w/ the logging exporter from both the metric gatherer as well as a basic collector setup seems to suggest this isn't what the gatherer is reporting:

```
Descriptor:
     -> Name: jvm.memory.pool.init
     -> Description: current memory pool usage
     -> Unit: by
     -> DataType: Gauge
NumberDataPoints #0
Data point attributes:
     -> name: STRING(PS Eden Space)
StartTimestamp: 2021-12-13 20:05:22.86 +0000 UTC
Timestamp: 2021-12-13 20:10:32.624 +0000 UTC
Value: 16777216
NumberDataPoints #1
Data point attributes:
     -> name: STRING(Metaspace)
StartTimestamp: 2021-12-13 20:05:22.86 +0000 UTC
Timestamp: 2021-12-13 20:10:32.624 +0000 UTC
Value: 0
```

From the parent ops-agent issue I'd suspect this is an edge case with the otlp receiver or one of the processors that is being used (would warrant some investigation and an issue in the collector contrib project). Can you confirm that you are seeing this with a processor-less configuration?

collector config:

```
exporters:
   logging:
     loglevel: debug
receivers:
   otlp:
     protocols:
       grpc:
service:
  pipelines:
    metrics:
      receivers:
        - otlp
      exporters:
        - logging
```

gatherer properties:

```
otel.metrics.exporter = otlp
otel.exporter.otlp.endpoint = http://localhost:4317
```

**Comment by sophieyfang** [comment]
You are right. Without any processors, there is no such issue. The culprit is `metricstransform/jvm__pipeline_jvm__metrics_1`

Great thanks!
