### ISSUE TITLE
[Maven Extension] Otel Maven Extension is not reporting its version as `otel.library.version`

### ISSUE THREAD

**Issue by cyrille-leclerc** [open-telemetry/opentelemetry-java-contrib#152]
**Is your feature request related to a problem? Please describe.**

Otel Maven Extension is not reporting its version as `otel.library.version`

**Describe the solution you'd like**

Add the OTel Plugin version using `OpenTelemetry.getTracer(instrumentName, instrumentVersion)`.

**Describe alternatives you've considered**

N/A

**Additional context**

**Comment by trask** [comment]
> Pending question: is there a standardised way to report this version number?

I believe the standard way would be to report this as the `instrumentationVersion` (when constructing the `Tracer`).

Check out

https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/dba6e429e4ff437e386a07a1d101c57f2b232b44/instrumentation-api/src/main/java/io/opentelemetry/instrumentation/api/instrumenter/Instrumenter.java#L111-L112

and

https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/dba6e429e4ff437e386a07a1d101c57f2b232b44/instrumentation-api/src/main/java/io/opentelemetry/instrumentation/api/InstrumentationVersion.java#L9-L10

(and https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#get-a-tracer)
