### ISSUE TITLE
[Baggage Processor] Introduce a `BaggageLogRecordProcessor` for parity with the `BaggageSpanProcessor `

### ISSUE THREAD

**Issue by cyrille-leclerc** [open-telemetry/opentelemetry-java-contrib#1577]
### Is your feature request related to a problem? Please describe.

In many use cases such as multi tenant applications, it is very helpful to use the Baggage API to propagate context across requests and to enrich the telemetry with these baggage attributes.
If it is possible today to enrich span attributes with baggage entries using `-D
otel.java.experimental.span-attributes.copy-from-baggage.include=...` and the [`BaggageSpanProcessor`](https://github.com/open-telemetry/opentelemetry-java-contrib/blob/v1.41.0/baggage-processor/src/main/java/io/opentelemetry/contrib/baggage/processor/BaggageSpanProcessor.java), there is no equivalent to enrich log attributes.

### Describe the solution you'd like

A `BaggageLogRecordProcessor` configurable through  `-D
otel.java.experimental.log-attributes.copy-from-baggage.include=...` to replicate what we have for spans.

**Comment by trask** [comment]
@cyrille-leclerc is this resolved now by #1576?

**Comment by cyrille-leclerc** [comment]
Correct, https://github.com/open-telemetry/opentelemetry-java-contrib/pull/1576 resolves this enhancement request.
