### ISSUE TITLE
Request for a few additional component owners

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-contrib#174]
We would like to have (at least) 2 owners for each component in this repository. The component owners will be automatically assigned to review PRs that touch files in those components.

`aws-xray`, `jfr-streaming`, `maven-extension`, and `runtime-attach` have (at least) 2 owners already.

`jmx-metrics` needs one additional owner - @Mrod1598 would you be interested? @rmfitzpatrick any other recommendations for people we could ask?

`contrib-samplers` also needs one additional owner - any volunteers?

`disruptor-processor` currently has no owners - @bogdandrutu are you still interested in this component?

**Comment by Mrod1598** [comment]
Yes, I'd be interested!

**Comment by trask** [comment]
> Yes, I'd be interested!

@Mrod1598 awesome, can you request membership into the OpenTelemetry github org? here's the instructions: https://github.com/open-telemetry/community/blob/main/community-membership.md#member. you can put myself and @anuraag as the two sponsors. being a member of the OTel org will allow us to assign you as a reviewer for the jmx-metrics component. thx!

**Comment by dehaansa** [comment]
I'd be happy to join the `jmx-metrics` owners as well if you'd like another. I've contributed a bit there, and helped @Mrod1598 work through some issues on some of his contributions as well. Also haven't applied for membership yet but I've got one sponsor ready, so if anyone here would like to sponsor me as well I'd be happy to take that assistance.

**Comment by trask** [comment]
> I'd be happy to join the `jmx-metrics` owners as well if you'd like another. I've contributed a bit there, and helped @Mrod1598 work through some issues on some of his contributions as well. Also haven't applied for membership yet but I've got one sponsor ready, so if anyone here would like to sponsor me as well I'd be happy to take that assistance.

Great, please add me as a sponsor!

**Comment by trask** [comment]
Closing, all components except `disruptor-processor` have (at least) two owners, and I have opened separate issue to track that.

Thanks everyone!
