### ISSUE TITLE
Triaging issues with `comp:xxx` labels similarly to what otel-collector-contrib does 

### ISSUE THREAD

**Issue by cyrille-leclerc** [open-telemetry/opentelemetry-java-contrib#182]
**Is your feature request related to a problem? Please describe.**

It's hard today to see which issue is associated to which component (e.g. `aws-xray`, `jfr-streaming`, `jmx-metrics`, `maven-extension`, `runtime-attach`...).

**Describe the solution you'd like**

Could we simplify this triaging process considering adopting the solution chosen by the [OpenTelemetry Collector Contrib](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues) repo with the `comp:xxx` labels (see [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/labels?q=comp%3A))?

Our labels could lok like:
* `comp:aws-xray`
* `comp:jfr-streaming`
* `comp:jmx-metrics`
* `comp:maven-extension`
* `comp:runtime-attach`
* `comp:samplers`

**Describe alternatives you've considered**

**Additional context**

**Comment by trask** [comment]
good idea, labels created!

**Comment by trask** [comment]
closing, labels have been added to existing issues
