### ISSUE TITLE
[Maven extension] cant set service name

### ISSUE THREAD

**Issue by delanym** [open-telemetry/opentelemetry-java-contrib#183]
I want to set the service.name to something other than Maven.

`.\mvnw.cmd  -e clean install --threads 3 -Dotel.traces.exporter=otlp -Dotel.exporter.otlp.endpoint=http://10.1.0.203:4317 -Dotel.instrumentation.maven.mojo.enabled=false -Dmaven.ext.class.path=c:\opt\opentelemetry-maven-extension-1.10.0-20220112.132157-1.jar -Dotel.resource.attributes=service.name=cats,service.namespace=mammals -Dotel.service.name=django`

In this line I've set the service name in 2 ways, but neither of them seems to have any effect
https://github.com/open-telemetry/opentelemetry-java/tree/main/sdk-extensions/autoconfigure

What am I doing wrong?

**Comment by cyrille-leclerc** [comment]
Should be fixed by https://github.com/open-telemetry/opentelemetry-java-contrib/pull/184

**Comment by delanym** [comment]
It looks fixed, but it also looks like there's no longer a default "maven".

**Comment by cyrille-leclerc** [comment]
@delanym can you please verify it's fixed with v1.10.0?

**Comment by delanym** [comment]
@cyrille-leclerc I've checked it on v1.10.0-alpha

**Comment by delanym** [comment]
@cyrille-leclerc is it possible to set the service name to the runner when using -T3 etc? Similar to what you get with MAVEN_OPTS="-Dorg.slf4j.simpleLogger.showThreadName=true"

**Comment by cyrille-leclerc** [comment]
> @cyrille-leclerc is it possible to set the service name to the runner when using -T3 etc? Similar to what you get with `MAVEN_OPTS="-Dorg.slf4j.simpleLogger.showThreadName=true"`

`service.name` should be settable using the `-Dotel.service.name=my-maven` system property

See https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk-extensions/autoconfigure/README.md#opentelemetry-resource

**Comment by delanym** [comment]
@cyrille-leclerc im asking for something else #209
