### ISSUE TITLE
Unable to push to PR branch

### ISSUE THREAD

**Issue by rmfitzpatrick** [open-telemetry/opentelemetry-java-contrib#197]
**Description**
When trying to update https://github.com/open-telemetry/opentelemetry-java-contrib/pull/190 with PR feedback I found I was unable to push my changes. This occurs with simple additions and after rebasing the branch and attempting to force push:

```
remote: Resolving deltas: 100% (4/4), completed with 4 local objects.
remote: error: GH006: Protected branch update failed for refs/heads/jmxremovemanualflush.
remote: error: Required status check "EasyCLA" is expected.
To github.com:open-telemetry/opentelemetry-java-contrib.git
 ! [remote rejected] jmxremovemanualflush -> jmxremovemanualflush (protected branch hook declined)
error: failed to push some refs to 'github.com:open-telemetry/opentelemetry-java-contrib.git'
```

I am not too familiar with the EasyCLA process but it appears its status check must have been considered successful for local branches with the current protection rule. It is possible I'm doing something incorrectly.

**Comment by trask** [comment]
ya, this was a recent change from CNCF to apply branch protection rules to all branches in the repo, it should work if you push the branch to your fork and submit PR from there

**Comment by anuraaga** [comment]
It looks like the `jmxremovemanualflush` branch was created in this repo, not a fork, which causes that check to kick in. Not sure why you'd be able to send a PR and then not add any updates to it, but either way let's make sure to write code on our fork except maybe for tiny README updates.

**Comment by trask** [comment]
> Not sure why you'd be able to send a PR and then not add any updates to it

it's the force push that's the problem
