### ISSUE TITLE
jmx-metrics: Integration Tests don't pass locally without bumping timing for waiting for metrics to 120s

### ISSUE THREAD

**Issue by Mrod1598** [open-telemetry/opentelemetry-java-contrib#200]
**Description**
In the `waitAndAssertMetrics` function We give it at most `30s` to get metrics but locally that never seems to be enough. 

```
KafkaIntegrationTest$KafkaConsumerIntegrationTest > endToEnd() FAILED
    org.awaitility.core.ConditionTimeoutException: Assertion condition defined as a io.opentelemetry.contrib.jmxmetrics.AbstractIntegrationTest 
    Expecting actual not to be empty within 30 seconds.
```

It's not isolated to kafka, it's all integrations.

**Steps to reproduce**
Set Docker Resources to: 
![image](https://user-images.githubusercontent.com/14144136/149793948-d9a39215-0d8d-4d76-85da-b8e6edcb409c.png)

run `./gradlew integrationTest`

**Expectation**
Integration tests pass

**Proposed Solution**
Bump the duration to `120s` most integration tests won't hit this on actions as it has a lot more room to work with so it'd only affect local development.

**Comment by rmfitzpatrick** [comment]
30s is a fair amount of time for the gatherer to report metrics. It may be better for the gatherer container to wait for a more informative log (adding one if necessary) that reaching the target mbean server has been successful before starting the test.

**Comment by rmfitzpatrick** [comment]
@Mrod1598 does https://github.com/open-telemetry/opentelemetry-java-contrib/pull/219 work any better for you?

**Comment by Mrod1598** [comment]
> @Mrod1598 does #219 work any better for you?

Sorry, been out of the office for a few days. yes that seems to be better.
