### ISSUE TITLE
Provide proper documentation for runtime attach mechanism

### ISSUE THREAD

**Issue by iNikem** [open-telemetry/opentelemetry-java-contrib#217]
Together with clear description of possible problems when using it.

**Comment by jeanbisutti** [comment]
Would it be solved with #354? [The new Readme.](https://github.com/open-telemetry/opentelemetry-java-contrib/blob/main/runtime-attach/README.md) Something more expected?

**Comment by trask** [comment]
thx! closing as resolved by #354
