### ISSUE TITLE
[Maven Extension] Extension doesn't refresh its config across multiple executions with `mvnd`

### ISSUE THREAD

**Issue by cyrille-leclerc** [open-telemetry/opentelemetry-java-contrib#220]
**Description**

Otel Maven extension doesn't refresh its config across multiple executions with `mvnd`.

It's caused by the fact that the SDK is recycled across multiple executions even if the passed configuration has changed.

The problem in the implementation seems to be that we tear down the SDK with `io.opentelemetry.maven.OpenTelemetrySdkService#dispose` on `org.codehaus.plexus.personality.plexus.lifecycle.phase.Disposable#dispose` when we should also tear/down and recreate on `io.opentelemetry.maven.OtelExecutionListener#sessionStarted` if the configuration of the new execution (env vars + system properties) is different from the previously used configuration.

**Steps to reproduce**

```
export OTEL_TRACES_EXPORTER="otlp"
export OTEL_SERVICE_NAME="maven-1"
mvnd verify
export OTEL_SERVICE_NAME="maven-2"
mvnd verify
```

TODO verify that it can be reproduced with the sequence above and that the service.name remains "maven-1" instead of becoming "maven-2" for the second invocation.

**Expectation**

The two traces use different "service.name": "maven-1" then "maven-2"

**What applicable config did you use?**

See description above

**Relevant Environment Information**

* opentelemetry-maven-extension 1.10.0-alpha

**Additional context**

**Comment by delanym** [comment]
Its working in 1.10.0-alpha @cyrille-leclerc I think the second time I tried I didn't have the updated extension

**Comment by cyrille-leclerc** [comment]
Thanks @delanym , do you think we can close this defect?
