### ISSUE TITLE
Which repo?

### ISSUE THREAD

**Issue by aceeric** [open-telemetry/opentelemetry-java-contrib#235]
Folks - I'm unclear when one would use this project as compared to https://github.com/open-telemetry/opentelemetry-java-instrumentation. In our use case, we have a packaged Java app running in Kubernetes and we want to add metrics collection by Prometheus with minimal effort: we simply want to expose metrics from each container running the app, and let Prometheus scrape and aggregate across the cluster. This repo uses an additional jar running on the machine, and the other project uses the standard JMX agent. This repo looks to focus on a smaller number of metrics categories. For a use case in which we will only monitor a JVM in one container, and will use prometheus to gather up the metrics Kubernetes wide - it's hard for me to tell which of these projects would be a better fit. Thank you for any guidance.

**Comment by rmfitzpatrick** [comment]
I'm not sure I can provide a definitive answer for your use case, if you're using JMX, the JMX metric gatherer and its built-in target system scripts of this project generate metrics from mbeans provided by target servers (remote processes): https://github.com/open-telemetry/opentelemetry-java-contrib/tree/main/jmx-metrics/docs/target-systems. I'm not aware of any JMX-based metric capabilities in the agent at present but could be mistaken (@trask?). I believe if you've already instrumented your app w/ the otel api or micrometer and run your app with the agent, meter providers and exporters are automatically created for you to create and export your metrics.

**Comment by trask** [comment]
> I'm not aware of any JMX-based metric capabilities in the agent at present but could be mistaken

This is correct. The javaagent captures just a couple of JMX-based metrics today (memory and gc).

**Comment by aceeric** [comment]
Thank you.
