### ISSUE TITLE
Attaching jars to the release

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-contrib#257]
Currently we attach `jmx-metrics` and `maven-extension` jars to the release.

Based on the [release artifact download counts](https://tooomm.github.io/github-release-stats/?username=open-telemetry&repository=opentelemetry-java-contrib), it looks like we could probably drop the `maven-extension` download, which I think makes sense, as most users probably consume that via maven central.

`jmx-metrics` release artifact downloads are lower than maven central downloads of `jmx-metrics` (unfortunately no public link for that), so maybe people are consuming that via maven central? or is the recommended approach to consume the `jmx-metrics` component via collector contrib? (though it looks like that's still on a pretty old version so maybe not(?))

Curious what others think?

**Comment by trask** [comment]
> With the jmx metric gatherer being a runnable uber jar I think releasing through GH can be convenient

thx, ya, this makes sense to me, and is similar to why we release the javaagent through GH also

> if there are operational or cost reasons to avoid doing so I'm ok with it just being in maven central

it's just some extra one-off yaml code in the release script, not a big deal

@cyrille-leclerc wdyt about the maven-extension?

**Comment by cyrille-leclerc** [comment]
> Based on the [release artifact download counts](https://tooomm.github.io/github-release-stats/?username=open-telemetry&repository=opentelemetry-java-contrib), it looks like we could probably drop the `maven-extension` download, which I think makes sense, as most users probably consume that via maven central.

@trask  I fully support your point, the opentelemetry-maven-extension belong to the Maven ecosystem so the natural way to download it is to go through Maven Central.
Side note: the only reason I see to not download through Maven Central is to use a non released version, to use a snapshot, and making snapshots downloadable is not solved by attaching the Otel Maven Extension to the GitHub Release.

**Comment by trask** [comment]
> the opentelemetry-maven-extension belong to the Maven ecosystem so the natural way to download it is to go through Maven Central

👍 I will update release workflow before next release

> by the way, do we have download stats from Maven Central?

ya, ping me any time I can pull them:

![image](https://user-images.githubusercontent.com/218610/158656885-d4144c65-019a-4234-b757-68ab8bcebd68.png)

**Comment by cyrille-leclerc** [comment]
Thanks @trask , these numbers are encouraging.
