### ISSUE TITLE
Update JMX reported metrics

### ISSUE THREAD

**Issue by carlosalberto** [open-telemetry/opentelemetry-java-contrib#291]
I've opened a pair of PRs to include the existing JMX metrics for JVM and Kafka Producer/Brokers. I'd love to have the review by the codeowners - specially as I'd like to go over the rest of the metrics, and I don't want that to be a surprise later.

* [JVM metrics](https://github.com/open-telemetry/opentelemetry-specification/pull/2478)
* [Kafka metrics](https://github.com/open-telemetry/opentelemetry-specification/pull/2485)

@dehaansa @Mrod1598 @rmfitzpatrick

**Comment by dehaansa** [comment]
@carlosalberto initially these additions look good, but it may be prudent to wait until the conversations around the long term support for the JMX metrics gatherer are further along (see #282)

**Comment by carlosalberto** [comment]
Thanks @dehaansa - I think there's value in defining them anyway, as we will need them one way or another.

Also, it may to your interest specifically that I'd like to (as mentioned in the PR) change some of the metrics from Gauges to UpDownCounters.

(On a related note, FYI, the used/committed/etc memory uses a different set of metrics in the [OTel Specs](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/semantic_conventions/runtime-environment-metrics.md#jvm-metrics), so I will sending a PR to adjust that in the jmx-metrics subproject.

**Comment by carlosalberto** [comment]
@dehaansa You maybe interested in the latest iterations in https://github.com/open-telemetry/opentelemetry-specification/pull/2485 - so far:

* Most gauges have become UpDownCounters
* Have left out of the semantic conventions a few metrics that can be synthesized as summary/histogram data points.

**Comment by breedx-splk** [comment]
Hey @carlosalberto -- this issue has been around for a while, and I think everything that's been linked to has been merged. Is there anything else actionable on this, or can we close it? 🙏🏻 Thanks.
