### ISSUE TITLE
Run a single JMX integration test

### ISSUE THREAD

**Issue by carlosalberto** [open-telemetry/opentelemetry-java-contrib#324]
Currently it is taking **a lot** to run the integration testing step of the JMX Gatherer - is there a chance to run a single one?

E.g. I'm trying to update the JVM ones only, and I'd like to restrict the test to that.

**Comment by anuraaga** [comment]
Hi @carlosalberto - do you mean for local development? You should be able to run `JvmTargetSystemIntegrationTest` by itself in an IDE.

**Comment by carlosalberto** [comment]
Hey @anuraaga!

Yes, local testing - no, sadly I don't run an IDE ;) But your comment makes me believe no build refactoring/extension is needed, and probably I can dig how to trigger this from gradle itself ;)

**Comment by rmfitzpatrick** [comment]
I think you're looking for [the filter](https://docs.gradle.org/current/userguide/java_testing.html#test_filtering) `./gradlew integrationTest --tests JvmTargetSystemIntegrationTest`

**Comment by breedx-splk** [comment]
I think @rmfitzpatrick has solved it. Please reopen if this doesn't work for you @carlosalberto.
