### ISSUE TITLE
Memory control

### ISSUE THREAD

**Issue by dino-ma** [open-telemetry/opentelemetry-java-contrib#375]
In view of the fact that our indicators are accumulated in memory and reported, do we have any strategies to avoid affecting business services

So if it is an online service with massive traffic, such as our company Baidu. There may be a risk of exploding the memory during this refresh window period

**Comment by dino-ma** [comment]
> 

Thank you for your response. I am not referring to an indicator. Instead, when our opentelemetry-java-contrib collects metrics in memory for flush, there may be a flush interval that fills up the container's memory, rendering the service unavailable. For this scenario, we consider whether the underlying component controls the overall memory usage of the component as a pool or threshold.

**Comment by dino-ma** [comment]
> Are you referring to metrics? If so there are a couple options to control memory usage:
> 
> 1. [Views](https://opentelemetry.io/docs/instrumentation/java/manual/#views) provide the ability to limit the set of attribute keys that are retained on instruments. If you have a high cardinality attribute contributing to high memory usage, you can filter it out.
> 2. [Aggregation temporality](https://opentelemetry.io/docs/instrumentation/java/manual/#views) controls allow an exporter to indicate whether it wants metrics in cumulative or delta temporality. The default, cumulative, means that each metric is a running total of all measurements ever recorded. In contrast, delta metrics only include measurements since the last collection. Backends have various requirements around temporality. Generally though, cumulative implies higher memory usage since it requires retaining data in memory for series that may not have received recent measurements.
> 3. Each metric has a hard code cardinality cap of 2000. This provides some protection against misbehaving instrumentation.

Thank you for your response. I am not referring to an indicator. Instead, when our opentelemetry-java-contrib collects metrics in memory for flush, there may be a flush interval that fills up the container's memory, rendering the service unavailable. For this scenario, we consider whether the underlying component controls the overall memory usage of the component as a pool or threshold.

**Comment by trask** [comment]
hi @dino-ma! @jack-berg above is referring to the controls that the OpenTelemetry SDK has in place to limit its memory consumption when collecting metrics (prior to flushing them).

if this isn't what you are asking about, maybe you can describe what you mean by "our indicators", and what in-memory telemetry components you are concerned about?

**Comment by dino-ma** [comment]
Hello, @trask  What I want to ask is that we use opentelemetry Java contrib as the SDK of otel. As for trace collection, there will be memory occupation in the process. Do we have a strategy for this scenario. This is not to say that we monitor and visualize the memory of applications in terms of indicators.

For example, the maximum memory of my current pod is 8g, and our application occupies 5g. If our opentelemetry Java contrib occupies 3.1g when collecting trace information, our application may be unavailable. In this scenario, do we have a thorough policy to ensure that we will not affect the business process.

  报错 笔记

**Comment by trask** [comment]
> do we have a thorough policy to ensure that we will not affect the business process.

if you are asking about metrics memory retention, then yes, I believe @jack-berg answers this above

if you are asking about span memory retention, each individual spans is only retained for the life and then flushed, e.g. to the BatchSpanProcessor which also has (configurable) memory limit policies

**Comment by dino-ma** [comment]
> > do we have a thorough policy to ensure that we will not affect the business process.
> 
> if you are asking about metrics memory retention, then yes, I believe @jack-berg answers this above
> 
> if you are asking about span memory retention, each individual spans is only retained for the life and then flushed, e.g. to the BatchSpanProcessor which also has (configurable) memory limit policies


Thank you for your support. It has been solved. In the future, we plan to provide a sapmler for Jaeger remote sample
