### ISSUE TITLE
Skywalking Exporter should support pipeline type traces

### ISSUE THREAD

**Issue by jxplus** [open-telemetry/opentelemetry-java-contrib#393]
Exporter skywalking only support logs and metrics，but no traces。

As a top project of apache，and a good product of Opentracing implementation，should also support traces。

**Comment by trask** [comment]
hi @jxplus! the skywalking exporter lives in a different repo: https://github.com/open-telemetry/opentelemetry-collector-contrib

**Comment by jxplus** [comment]
i see, thanks.
