### ISSUE TITLE
Static instrumenter may be broken since 1.18.0

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-contrib#436]
The static instrumenter artifacts are not yet published, so this is not urgent, but wanted to open tracking issue so not forgotten about. I had to disable its `JarTest` which was failing after updating to 1.18.0.

**Comment by jeanbisutti** [comment]
Can you please assign this issue to me? The problem seems to come from the way the test is written. It does not seem to be a regression. I could create a PR later tomorrow.
