### ISSUE TITLE
Target Micrometer 1.5

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-contrib#476]
Is there any reason we're targeting 1.1 here? Micrometer 1.1 is super old, and not compatible with the more recent releases - the API stabilized around 1.5, and since then all the changes have been strictly incremental. Before that there's been a few breaking changes.

_Originally posted by @mateuszrzeszutek in https://github.com/open-telemetry/opentelemetry-java-contrib/pull/472#discussion_r978392934_

**Comment by HaloFour** [comment]
Sounds good to me, my concern was to target a version that would apply to a critical mass of users.

**Comment by HaloFour** [comment]
I doesn't seem like any of the APIs I'm using have changed since 1.1.  That's why I was targeting latest for tests, to ensure that it would continue to work with the latest version.  I also recall that breaking changes is why I target 1.1 instead of 1.0.

**Comment by trask** [comment]
@mateuszrzeszutek are you good with closing this and keeping the current state?

**Comment by mateuszrzeszutek** [comment]
Yeah, let's close it 👍
(it's too bad we don't have anything like muzzle here that'd verify that we're compatible with all versions)
