### ISSUE TITLE
No Class in opentelemetry-runtime-attach jar

### ISSUE THREAD

**Issue by jufab** [open-telemetry/opentelemetry-java-contrib#508]
**Description**
I wanted to try opentelemetry-runtime-attach module. 
I import it in maven project.
But when I would like to import `RuntimeAttach` : there is no class.
In jar, there is only otel-agent.jar in `io.opentelemetry.contrib.attach`

**Steps to reproduce**
[Just open jar from maven and see the content](https://search.maven.org/remotecontent?filepath=io/opentelemetry/contrib/opentelemetry-runtime-attach/1.18.0-alpha/opentelemetry-runtime-attach-1.18.0-alpha.jar)

**Expectation**
Find RuntimeAttach.class  in jar

**Relevant Environment Information**
Version: 1.18.0-alpha (but doesn't exist since 1.16.0-alpha)
OS: Ubuntu 20.04
Maven: 3.6.3

**Comment by jeanbisutti** [comment]
Hi Julien,
I have created a PR to fix this. The correction should be included in the next release which should take place in the next two weeks.
