### ISSUE TITLE
Artifact aws-resources lost

### ISSUE THREAD

**Issue by altro3** [open-telemetry/opentelemetry-java-contrib#532]
Can't find it in maven central:
![изображение](https://user-images.githubusercontent.com/48474279/195949137-dd811240-099a-4790-87bd-0accff392337.png)

**Comment by jack-berg** [comment]
This was a mistake. Here's the [line](https://github.com/open-telemetry/opentelemetry-java-contrib/blob/main/aws-resources/build.gradle.kts#L5) that caused the problem.

**Comment by altro3** [comment]
@jack-berg I see.... But do you plan to fix this in release 1.1.9.0 or will we have to wait for release 1.20.0?

**Comment by jack-berg** [comment]
We published a patch release [1.19.1](https://github.com/open-telemetry/opentelemetry-java-contrib/releases/tag/v1.19.1) to fix this omission. Thanks for the report!
