### ISSUE TITLE
Feature Request: Centralized sampling for ADOT SDK

### ISSUE THREAD

**Issue by TheRealGoku** [open-telemetry/opentelemetry-java-contrib#58]
Feature request to support sampling logic in ADOT sdk as similar like what has been currently offered in X-Ray SDK.

I see the code is in progress over here https://github.com/open-telemetry/opentelemetry-java-contrib/tree/main/aws-xray/src/main/java/io/opentelemetry/contrib/awsxray

Raising this for tracking purpose.

**Comment by trask** [comment]
hi @TheRealGoku, what is ADOT sdk?

**Comment by TheRealGoku** [comment]
"AWS Distro for OpenTelemetry" SDK https://aws-otel.github.io/docs/getting-started/java-sdk

**Comment by iNikem** [comment]
> "AWS Distro for OpenTelemetry" SDK https://aws-otel.github.io/docs/getting-started/java-sdk

If you are asking for a feature in AWS Distro, then probably that should go to their issue tracking.

**Comment by TheRealGoku** [comment]
Done, Thanks https://github.com/aws-observability/aws-otel-java-instrumentation/issues/69
