### ISSUE TITLE
Reliable RED metrics extraction from traces

### ISSUE THREAD

**Issue by MaheshGPai** [open-telemetry/opentelemetry-java-contrib#638]
**Is your feature request related to a problem? Please describe.**
R - Request Rate
E - Request Error
D - Request Duration
RED metrics extraction from traces provide excellent insight into the health of a micro-service. RED metrics extraction predominantly occurs at the tracing backed which receives and process all the spans. But this can be problematic as most of the service owners would exercise trace sampling to control the volume of trace data emitted. So metrics extracted out of sampled traces are not accurate and reliable

**Describe the solution you'd like**

1. Implement a delegated sampler that ensures that all non-sampled spans are marked for RECORDING.
2. Implement a custom SpanProcessor which captures the RED metrics & any other metrics (trace count, active span count etc..) by hooking on to the onEnd event of a span, using a OTEL MetricProvider

If this is acceptable, I plan to contribute this to the repo.

**Describe alternatives you've considered**

**Additional context**

**Comment by trask** [comment]
hi @MaheshGPai! if you are looking for http metrics, check out https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/semantic_conventions/http-metrics.md
