### ISSUE TITLE
Latest JMX gatherer broken with collector JMX receiver

### ISSUE THREAD

**Issue by jsuereth** [open-telemetry/opentelemetry-java-contrib#72]
JMX Gatherer 1.4.x release is unable to communicate with the collector (last collector release doesn't support latest OTLP metric attributes).

I think this could be fixed by bumping to 1.5.x where both labels + attributes are sent (or we can wait for the next collector version which will support full OTLP 0.9).

**Comment by jkwatson** [comment]
FYI, 1.4.1 writes both attributes and labels: https://github.com/open-telemetry/opentelemetry-java/releases/tag/v1.4.1

**Comment by jsuereth** [comment]
I'll have to do some more diagnostics then, interesting.  The current collector integration tests is still pulling the 1.0-alpha, a quick update to that should be enlightening.

**Comment by jsuereth** [comment]
Actually, I updated the integration tests, and this appears to not be a problem.

I'm working on the integration tests for the collector component to be able to pull in multiple versions of the jar agent to test compatibility.  However, I noticed 1.4.x is not published on maven central.  Was that on purpose?

**Comment by rmfitzpatrick** [comment]
@jsuereth the artifact has since been renamed: https://repo1.maven.org/maven2/io/opentelemetry/contrib/opentelemetry-jmx-metrics/1.4.0-alpha/opentelemetry-jmx-metrics-1.4.0-alpha.jar

**Comment by jsuereth** [comment]
ah, need to update the README to point at the new location

**Comment by anuraaga** [comment]
Sent #75 to fix the README hopefully. Will close this issue then since sounds like we're good on the compatibility front

**Comment by jsuereth** [comment]
Also, as an FYI - we should be able to update integration tests on the collector side each release here: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/5176
