### ISSUE TITLE
Whether a span pressure test report can be generated

### ISSUE THREAD

**Issue by dino-ma** [open-telemetry/opentelemetry-java-contrib#766]
**Description**
We implemented TraceAgent using AOP based on opentelemetry-java-contrib. However, at present, it takes about 0.26ms to generate each SPAN under the pressure test scenario. Our business scenario is relatively complex. If there are hundreds of SPANs generated by one HTTP call, 0.26ms is unacceptable.

**Detail**

``

**Comment by trask** [comment]
hi @dino-ma, which contrib component(s) are you using?
