### ISSUE TITLE
Donating a Maven OpenTelemetry extension to the OpenTelemetry project?

### ISSUE THREAD

**Issue by cyrille-leclerc** [open-telemetry/opentelemetry-java-contrib#78]
Noter that this message is a cross post of https://github.com/open-telemetry/community/discussions/832 as suggested by @trask .

---

Dear community,

We would like to donate to the OpenTelemetry project a [Maven OpenTelemetry extension](https://github.com/elastic/opentelemetry-maven-extension) that we have created to observe the execution of Maven builds.

This Maven instrumentation integrates with other OpenTelemetry capable CI/CD tools such as Jenkins pipelines ([Jenkins OpenTelemetry plugin](https://github.com/jenkinsci/opentelemetry-plugin)), Ansible deployments ([Ansible OpenTelemetry plugin](https://github.com/ansible-collections/community.general/pull/3091)) or the [otel-cli](https://github.com/equinix-labs/otel-cli).
 
Here is an example of distributed trace providing visibility of a Jenkins / Maven CI pipeline.

![](https://raw.githubusercontent.com/cyrille-leclerc/opentelemetry-maven-extension/main/docs/images/jenkins-maven-execution-trace-jaeger.png)

It's very straightforward to test the extension on any existing Maven project as we have documented [here](https://github.com/elastic/opentelemetry-maven-extension#getting-started).

We have very positive feedback from CI/CD practitioners when we show the capabilities and the extension is already used by Elastic on its production CI platform in conjunction with the Jenkins OpenTelemetry plugin.

We would like to donate the Maven OpenTelemetry extension to the OpenTelemetry project / CNCF foundation because we feel that it would be the best place to develop this integration and because we see the opportunity to create an entire ecosystem of  OpenTelemetry capable CI/CD tools.

Note that we preferred to build this integration as a Maven extension rather than as an auto instrumentation that would be part of the [OpenTelemetry Java agent](https://github.com/open-telemetry/opentelemetry-java-instrumentation) because the Maven community is used to define its builds adding plugins and extension to build definitions (pom.xml) rather than wiring a Java auto-instrumentation agent when launching the "mvn" command.

**Would the OpenTelemetry Java Contrib project be interested in hosting such [Maven OpenTelemetry integration](https://github.com/elastic/opentelemetry-maven-extension)?**

Following the [donations guidelines](https://github.com/open-telemetry/community/blob/main/CONTRIBUTING.md#donations), I feel this donation can be qualified as a "small donation" and a simple Pull Request would then be enough.

**Comment by kenfinnigan** [comment]
Big +1 from me.

Could you create a PR to submit it to this repo?

**Comment by jkwatson** [comment]
By the way, I have something similar for gradle (very early days...needs lots of love, including being able to participate in larger build traces):  https://github.com/jkwatson/gradle-otel-tracing

**Comment by cyrille-leclerc** [comment]
Thanks for your support @kenfinnigan , I'm working on a PR, it's the opportunity for me to re-learn Gradle 👼

**Comment by cyrille-leclerc** [comment]
@kenfinnigan @jkwatson I submitted a PR for the donation:
https://github.com/open-telemetry/opentelemetry-java-contrib/pull/79

@jkwatson when you have time, I would love to discuss with you of the way you instrumented Gradle and present you some questions I faced when developing the Maven instrumentation

**Comment by jkwatson** [comment]
> @kenfinnigan @jkwatson I submitted a PR for the donation:
> https://github.com/open-telemetry/opentelemetry-java-contrib/pull/79
> 
> @jkwatson when you have time, I would love to discuss with you of the way you instrumented Gradle and present you some questions I faced when developing the Maven instrumentation
> 

Start by looking at the source I posted above. There's not much to it at the moment. :)

**Comment by trask** [comment]
@cyrille-leclerc if you are able to join the [Thu Java SIG meeting](https://calendar.google.com/event?action=TEMPLATE&tmeid=aDM0cDVuNHQ4a2RlM2NxaDRlN2NmcDRjbnNfMjAyMTA5MTZUMTYwMDAwWiBnb29nbGUuY29tX2I3OWUzZTkwajdiYnNhMm4ycDVhbjVsZjYwQGc&tmsrc=google.com_b79e3e90j7bbsa2n2p5an5lf60%40group.calendar.google.com&scp=ALL), @jkwatson @kenfinnigan me and others are usually there, and it's a great place to chat about stuff if you want

**Comment by cyrille-leclerc** [comment]
Thanks @trask I'll try to join this week otherwise it will be next week.

**Comment by trask** [comment]
Closed by #79
