### ISSUE TITLE
[maven-extension] Figure out how to leverage standard autoconfigure

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-contrib#82]
See comment in the original maven-extension PR about the technical challenges faced with using standard autoconfigure:

* https://github.com/open-telemetry/opentelemetry-java-contrib/pull/79#discussion_r712689149

**Comment by cyrille-leclerc** [comment]
I faced 2 distinct families of challenges:

* The Otel Auto Configurer assumes that Otel will be shutdown at the shutdown of the JVM which is not true when Otel is managed as an extension or a plugin of the system it instruments. The assumption of the Otel Auto Configurer is materialized by JVM shutdown hooks:
   * https://github.com/open-telemetry/opentelemetry-java/blob/v1.6.0/sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/TracerProviderConfiguration.java#L58
```java
Runtime.getRuntime().addShutdownHook(new Thread(tracerProvider::close)); 
```
   * https://github.com/open-telemetry/opentelemetry-java/blob/v1.6.0/sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/MetricExporterConfiguration.java#L151
```java
```


* registers JVM shutdown hooks that are incompatible

**Comment by cyrille-leclerc** [comment]
FYI we are migrating the Jenkins OpenTelemetry Plugin to the Otel SDK Auto. Configuration Extension.
It's working well so far. Some lessons learned.

* The pattern to do integration tests with autoconfigured in memory span and metrics exporters is not easy
* We need for the configuration to combine parameters from
   * Sensible defaults (e.g. service.name= "jenkins" or "maven")
   * Standard Auto Configuration System Properties and Environment variables
   * Configuration settings passed via the configuration mechanism of the integrated system (e.g. standard Jenkins plugin configuration mechanisms).

https://github.com/jenkinsci/opentelemetry-plugin/pull/185

I'll share more as we progress
