### ISSUE TITLE
[maven-extension] Add the OpenTelemetry Maven Extension to the Maven documentation

### ISSUE THREAD

**Issue by cyrille-leclerc** [open-telemetry/opentelemetry-java-contrib#83]
**Is your feature request related to a problem? Please describe.**

The Maven documentation lists the Maven extensions in [Apache/ Maven/ Available Extensions]https://maven.apache.org/extensions/index.html). The OpenTelemetry Maven Extension should be listed here

We should add the OpenTelemetry Maven extension to this documentation page for better visibility.

**Describe the solution you'd like**

Declare the OpenTelemetry Maven extension, it could look like:

| Extension | Maintainer | Description |
|-----------|-----------|-------------|
| opentelemetry | [The OpenTelemetry community](https://github.com/open-telemetry/opentelemetry-java-contrib/tree/main/maven-extension) | [OpenTelemetry](https://opentelemetry.io/) instrumentation of Maven builds capturing Maven mojo executions as distributed traces spans. |

**Describe alternatives you've considered**

Not documenting the OpenTelemetry extension on Maven website.

**Additional context**

N/A

**Comment by trask** [comment]
Sounds good, can you add link to this issue with your PR/jira/etc that requests the update to that page so we know how to do that in the future if needed?

**Comment by cyrille-leclerc** [comment]
I created this issue for tracking purpose. I propose that we wait and make the OpenTelemetry Maven extension more visible publicly after we have released a version to fix:
- https://github.com/open-telemetry/opentelemetry-java-contrib/issues/86

**Comment by cyrille-leclerc** [comment]
In progress with PR on Apache Maven docs: [Update "Maven/ Available Extensions", add OpenTelemetry Maven Extension apache/maven-site#271](https://github.com/apache/maven-site/pull/271)

**Comment by cyrille-leclerc** [comment]
Fix via https://github.com/apache/maven-site/pull/271 that has been merged
