### ISSUE TITLE
Contrib fails to start because of mismatched hashes

### ISSUE THREAD

**Issue by rohits-splunk** [open-telemetry/opentelemetry-java-contrib#832]
**Description**
I installed otel collector contrib ( v.75.0 ) today for using the JMX receiver and also downloaded the 1.25 jmx metrics receiver jar file .but it is complaining about this 

```Error: invalid configuration: receivers::jmx: invalid `jar_path`: jar hash does not match known versions
2023/04/18 21:19:58 collector server run finished with error: invalid configuration: receivers::jmx: invalid `jar_path`: jar hash does not match known versions```

**Steps to reproduce**
Provide a (runnable) recipe for reproducing the error.

**Expectation**
A clear and concise description of what you expected to see.

**What applicable config did you use?**
Config: (e.g. the yaml config file)

**Relevant Environment Information**
Version: (e.g., `v0.0.1`, `2bef20a`, etc.)
OS: (e.g., "Ubuntu 20.04")
Compiler (if manually compiled): (e.g., "openJDK 1.8.0_252")

**Additional context**

**Comment by rohits-splunk** [comment]
@trask  No it didnt resolve at all, i am still facing the same issue, i closed in order to try more . But if you have any resolution, please let me know.

**Comment by CzyerChen** [comment]
@rohits-splunk 
Did you resolve later?  I tried with 1.33 and had the same problem.
https://github.com/open-telemetry/opentelemetry-collector-contrib/discussions/31542

I'm new, and any help here? @trask

**Comment by CzyerChen** [comment]
> @rohits-splunk Did you resolve later? I tried with 1.33 and had the same problem. [open-telemetry/opentelemetry-collector-contrib#31542](https://github.com/open-telemetry/opentelemetry-collector-contrib/discussions/31542)
> 
> I'm new, and any help here? @trask

I tried with 1.32.0 again, and that worked just now.

```
:~$ docker run -v $(pwd)/otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml -v $(pwd)/opentelemetry-jmx-metrics.jar:/usr/local/opentelemetry-jmx-metrics.jar otel/opentelemetry-collector-contrib:latest
Error: invalid configuration: receivers::jmx: invalid `jar_path`: jar hash does not match known versions
2024/03/05 03:11:23 collector server run finished with error: invalid configuration: receivers::jmx: invalid `jar_path`: jar hash does not match known versions

## change opentelemetry-jmx-metrics.jar from 1.33.0 -> 1.32.0
$ docker run -v $(pwd)/otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml -v $(pwd)/opentelemetry-jmx-metrics.jar:/usr/local/opentelemetry-jmx-metrics.jar otel/opentelemetry-collector-contrib:latest
2024-03-05T03:16:33.342Z	info	service@v0.95.0/telemetry.go:55	Setting up own telemetry...
2024-03-05T03:16:33.348Z	info	service@v0.95.0/telemetry.go:97	Serving metrics	{"address": ":8888", "level": "Basic"}
2024-03-05T03:16:33.360Z	info	service@v0.95.0/service.go:143	Starting otelcol-contrib...	{"Version": "0.95.0", "NumCPU": 4}
2024-03-05T03:16:33.360Z	info	extensions/extensions.go:34	Starting extensions...
2024-03-05T03:16:33.370Z	info	service@v0.95.0/service.go:206	Starting shutdown...
2024-03-05T03:16:33.371Z	info	extensions/extensions.go:59	Stopping extensions...
2024-03-05T03:16:33.372Z	info	service@v0.95.0/service.go:220	Shutdown complete.
Error: cannot start pipelines: failed to parse Endpoint "192.168.2.60:1616": parse "192.168.x.x:1616": first path segment in URL cannot contain colon
2024/03/05 03:16:33 collector server run finished with error: cannot start pipelines: failed to parse Endpoint "192.168.2.60:1616": parse "192.168.x.x:1616": first path segment in URL cannot contain colon
```
