### ISSUE TITLE
jmx-metrics unable to connect to server with SSL enabled on the RMI registry

### ISSUE THREAD

**Issue by dmitchnewrelic** [open-telemetry/opentelemetry-java-contrib#834]
**Description**
The JMX Metric Gatherer is not working properly with servers that have SSL protection enabled on the RMI registry.  [Oracle's Java documentation](https://docs.oracle.com/javadb/10.10.1.2/adminguide/radminjmxenablepwdssl.html) describes this setting as follows: 

_The system property `com.sun.management.jmxremote.registry.ssl=true` was new in JDK 6 and aims at resolving security issues with the RMI registry used in relation with JMX. This property must be used in conjunction with `com.sun.management.jmxremote.ssl.need.client.auth=true` in order to fully secure the RMI registry._

**Steps to reproduce**
1. Configure a java server with the following settings: 

```
 -Dcom.sun.management.jmxremote.local.only=false 
 -Dcom.sun.management.jmxremote.password.file=jmxremote.password 
 -Dcom.sun.management.jmxremote.access.file=jmxremote.access 
 -Dcom.sun.management.jmxremote 
 -Dcom.sun.management.jmxremote.authenticate=true 
 -Dcom.sun.management.jmxremote.ssl.need.client.auth=true 
 -Dcom.sun.management.jmxremote.registry.ssl=true 
 -Dcom.sun.management.jmxremote.ssl=true 
 -Dcom.sun.management.jmxremote.port=1098 
 -Dcom.sun.management.jmxremote.rmi.port=1099 
 -Djava.rmi.server.hostname=localhost 
 -Djavax.net.ssl.keyStore=serverkeystore 
 -Djavax.net.ssl.keyStorePassword=<password> 
 -Djavax.net.ssl.trustStore=servertruststore 
 -Djavax.net.ssl.trustStorePassword=<password>
```

2. Configure the JMX Metric Gatherer to connect to the server using the following session.properties file: 

```
otel.jmx.service.url=service:jmx:rmi:///jndi/rmi://localhost:1098/jmxrmi
otel.jmx.target.system = kafka
otel.jmx.interval.milliseconds = 60000
otel.metrics.exporter = otlp
otel.exporter.otlp.timeout = 30000
otel.exporter.otlp.endpoint = http://localhost:4317
otel.jmx.username=<username>
otel.jmx.password=<password>
javax.net.ssl.keyStoreType=JKS
javax.net.ssl.keyStore=clientkeystore
javax.net.ssl.keyStorePassword=<password>
javax.net.ssl.trustStoreType=JKS
javax.net.ssl.trustStore=clienttruststore
javax.net.ssl.trustStorePassword=<password>
```
3. Run the JMX Metric Gatherer: 

` java -jar opentelemetry-jmx-metrics.jar -config session.properties`

**Expectation**
JMX metrics should be gathered from the server successfully and exported to the OpenTelemetry collector. 
We see the following exception instead: 

`java.io.IOException: Failed to retrieve RMIServer stub: javax.naming.CommunicationException [Root exception is java.rmi.ConnectIOException: non-JRMP server at remote endpoint]
`

The exception doesn't occur when ` -Dcom.sun.management.jmxremote.registry.ssl` is set to `false`. 

**What applicable config did you use?**

See contents of the `session.properties` file above. 

**Relevant Environment Information**
Version: v1.25.0
OS: Mac OS v12.6.1
Compiler (if manually compiled): n/a

**Additional context**
I'm working on a PR that addresses the issue.

**Comment by trask** [comment]
Resolved by #835
