### ISSUE TITLE
[Maven Extension] 1.25 versions not published to maven central and latest version link search with no result

### ISSUE THREAD

**Issue by zoranzaric-cpx** [open-telemetry/opentelemetry-java-contrib#853]
**Description**
I can't find 1.25.0 and 1.25.1 of the maven extension in maven central.

Also the "latest version" link int the extension's README (https://central.sonatype.com/search?q=g:io.opentelemetry.contrib%20%20a:opentelemetry-maven-extension&smo=true) doesn't give any results.

**Comment by trask** [comment]
hey @zoranzaric-cpx! this is what I get when I go to the URL above:

![image](https://user-images.githubusercontent.com/218610/234426146-3a40d240-ed8d-46b1-9fff-0286f0a5da4c.png)

**Comment by trask** [comment]
(and I can also see it here: https://repo1.maven.org/maven2/io/opentelemetry/contrib/opentelemetry-maven-extension/)

**Comment by zoranzaric-cpx** [comment]
Very strange… I really tried it several times.
Thanks!
