### ISSUE TITLE
Enable ability to overwrite mbean attribute value

### ISSUE THREAD

**Issue by akats7** [open-telemetry/opentelemetry-java-contrib#901]
### Component(s)

jmx-metrics

### Is your feature request related to a problem? Please describe.

We have a use case where we would like to create metrics for string attributes, it makes sense to not provide a string callback, it would be useful to be able to force a value in the instrument helper (just set the value equal to '1') or even better it would be if the InstrumentHelper also accepted a callback/closure that allows you to build logic to set the metric value to a long, double, or counter, when the mbean attribute itself is a different type.

### Describe the solution you'd like

I would like the InstrumentHelper constructor to accept a closure or callback function, that if set will be used to update the metric value based on the logic in the closure

e.g.,

```
def metric = otel.mbeans("RANDOM_MBEAN")
otel.instrument(metric, "metric_based_off_string",
        "description", "by",
        "string-metric",  checkValue ,otel.&longValueCallback)
```
```
def checkValue = { value ->
  if (value == "running") {
    return 1
  } else {
      return 0 
  }
} 
```

**Comment by trask** [comment]
cc: jmx-metrics component owners @breedx-splk @Mrod1598 @rmfitzpatrick @dehaansa

**Comment by dehaansa** [comment]
I don't see any issues with supporting this behavior, but I don't believe I will personally have time to implement it very soon.

**Comment by akats7** [comment]
> I don't see any issues with supporting this behavior, but I don't believe I will personally have time to implement it very soon.

@dehaansa I'd be willing to make the contribution

**Comment by breedx-splk** [comment]
@akats7 Sounds like string -> numeric isn't really the core goal, it sounds like a more general-purpose transformation mechanism. Please feel free to mention me on the PR and I'll review. Thanks!

**Comment by dehaansa** [comment]
I would agree that rmfitzpatrick's proposal would reduce the necessary added complexity to InstrumentHelper (an already very complex bit of functionality).

Adding the behavior to the MBeanHelper should just require a new attribute/constructor, and a relatively simple modification to the getAttribute/getAttributes functions, which does seem cleaner.

**Comment by akats7** [comment]
> I would agree that rmfitzpatrick's proposal would reduce the necessary added complexity to InstrumentHelper (an already very complex bit of functionality).
> 
> Adding the behavior to the MBeanHelper should just require a new attribute/constructor, and a relatively simple modification to the getAttribute/getAttributes functions, which does seem cleaner.

sounds good, @trask can I please be assigned this issue
