### ISSUE TITLE
[maven-extension] Disable Mojo spans

### ISSUE THREAD

**Issue by kenfinnigan** [open-telemetry/opentelemetry-java-contrib#97]
**Is your feature request related to a problem? Please describe.**
In playing with the extension today on a build of Quarkus, it generates 17400 spans as each Mojo/plugin in a module build has its own span.

Though this information is beneficial in diagnosing a problem it does add a lot more information than is probably necessary for regular project builds. It might also be interesting to provide a list of mojo names that should have spans and ignore the rest, so known plugins that are troublesome can always have spans created?

**Describe the solution you'd like**
Ability to turn off span creation at the mojo level. Which option should be the default is possibly another discussion.

**Describe alternatives you've considered**
It would be possible to provide a sampling strategy to exclude them, but I think it's better to prevent their creation in the first place if that's what is desired.

**Additional context**
Happy to work on a fix for this if there's interest and agreement

**Comment by cyrille-leclerc** [comment]
@v1v @kuisathaverat it reminds me the problem we faced on Jenkins observability. 17k span is one order of magnitude higher than the problem we faced in CI pipeline traces :-)
I like the idea to be incremental and first enable disabling bluntly the mojo spans. Later, we will be able to refine the feature to support smarter filtering if it makes sense.
Note that this telles me that the challenge will come when we add unit test visibility. One span per unit test?

**Comment by kenfinnigan** [comment]
Ok, I will start playing around with this when I have a moment.

Whether we need a span per unit test would depend on the purpose of the spans.

If it's purely as a view on how long a build is taking, does it need that really fine-grained level of a particular test? Or only all the tests and then recognize if a set of tests takes too long, to evaluate the logs for how long each test actually took to find the culprit?
